### ISSUE TITLE
Problem with IPFS file download

### ISSUE THREAD

**Issue by fasghq** [pinnaculum/aioipfs#1]
I try to get the NFT image (e.g. [https://ipfs.io/ipfs/QmVFPvu8aeJHXyNVxpfftVHaKjRsbtH6dXWscJ2TukM3xi](https://ipfs.io/ipfs/QmVFPvu8aeJHXyNVxpfftVHaKjRsbtH6dXWscJ2TukM3xi) ) from IPFS as follows:
1.  Run IPFS daemon
2.  Run small script:

```
async def main():
	client = aioipfs.AsyncIPFS()
	print(client)
	await client.core.get('QmVFPvu8aeJHXyNVxpfftVHaKjRsbtH6dXWscJ2TukM3xi', dstdir='/tmp')
	await client.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
I receive the following error:
Could not remove TAR file: [WinError 32] The process cannot access the file because it is being used by another process: 'file path'

**Comment by pinnaculum** [comment]
Hi @fasghq and sorry for the delay. I'm aware of this issue which happens, i believe, only when aioipfs is used on windows. This is due to a the temporary tar file not being properly closed i think, i'll provide a fix as soon as i can. Which python version are you using ?

Thank you for reporting the issue.

**Comment by pinnaculum** [comment]
> I receive the following error: Could not remove TAR file: [WinError 32] The process cannot access the file because it is being used by another process: 'file path'

So this is actually a warning message that's printed to stderr when it fails to remove the tar file received from the kubo daemon but it doesn't mean that it failed to get the object. Can you please check the return value of the *get()* coroutine call ? It should be *True* if the get call is successfull.

**Comment by fasghq** [comment]
Yes, I receive the needed file with `archive=False` flag. So, currently, I just ignore these errors. As I understood, it downloads these tar archieves on my `C:` drive and then struggles to remove them (I remove them manually).

**Comment by pinnaculum** [comment]
Ok. Yes, that's what's happening. Will publish a fix soon.

**Comment by pinnaculum** [comment]
> Yes, I receive the needed file with `archive=False` flag. So, currently, I just ignore these errors. As I understood, it downloads these tar archieves on my `C:` drive and then struggles to remove them (I remove them manually).

A fix was published on the [devel](https://github.com/pinnaculum/aioipfs/tree/devel) branch, and wasn't published to pypi yet. Are you able to try that branch and confirm that you don't get these messages now ? Thank you.
