### ISSUE TITLE
Py-test problems

### ISSUE THREAD

**Issue by ewi2345** [pinnaculum/aioipfs#2]
Greetings,
I am not sure when u did the last pytest run -- the tests don't work: 
1. At least, you need to include for event_loop for following code - or  nothing works.
@pytest.fixture
def event_loop():
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()
2. When a test failed it block the corresponding localhost ports - I get the following error:
* Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/9080) failed: listen tcp4 127.0.0.1:9080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
So (failed tests) occupy ports -- which means that, I assume sockets were used in a way that made them persistently bind itself to given ports. This may reveal a much bigger problem -- What happen to the ports in a production or app environment when the used "cmd" can't be closed - or the app must be restarted to have these locked ports being removed ...? I am not aware that there is an external tool that I can use to close these IP ports. 
Or:
3. how about using some auto-clean function like:
@pytest.fixture(autouse=True)
async def cleanup_after_test():
    yield
    - Perform cleanup actions, e.g., release ports
    - Close any remaining connections 
    - Ensure that all resources are properly released after each test
Just a thought
Best
Ike

**Comment by pinnaculum** [comment]
As we've discussed this by email (you didn't have pytest installed) i'll close this one. The GH CI workflow was fixed and tests python 3.7 to 3.11 on all platforms, you can see the Actions test runs [here](https://github.com/pinnaculum/aioipfs/actions). Thank you.
