### ISSUE TITLE
Error processing car file: car stream not convertible to bytes

### ISSUE THREAD

**Issue by dtbuchholz** [pinnaculum/aioipfs#3]
## Summary

I've followed the example to process a locally downloaded car file (see the cid [here](https://dweb.link/api/v0/ls?arg=bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4)) but cannot stream the file contents. It runs into an error: `car stream for ... not convertable to bytes`.

## Details 
Here's the example implementation from the docs:

```py
from pathlib import Path
from aioipfs import util

data = await util.car_bytes(
    util.car_open(Path('docs.car')),
    'bafybeiawyahkjt4kzrzc3bjylqupniukbpnbvys7pt536c64gxg7onq36m'
)
```

Here's my setup. After downloading the car file locally (it's V2 iirc), I try to drop it into the snippet above. I _can_ successfully use `car_open` (it shows the pointer to `<ipfs_car_decoder.async_stream.FileByteStream object at 0x104c97c90>`), but trying to run `car_bytes` is where the error is thrown.

```py
from pathlib import Path
from aioipfs import util
from asyncio import run

async def process_car_file():
    try:
        data = await util.car_bytes(
            util.car_open(Path('bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4.car')),
            "bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4",
        )
    except Exception as e:
        print(f"Error occurred: {e}")

run(process_car_file())
# Error occurred: car stream for bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4 not convertable to bytes
```

Note: the contents of the car file is two directory layers with a single file: `bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4/xm_data/p1/1700842786271269.parquet`

**Comment by pinnaculum** [comment]
@dtbuchholz Hello Dan. Thank you for providing your code.

This exception is raised by py-ipfs-car-decoder's *stream_bytes()* coroutine [here](https://github.com/kralverde/py-ipfs-car-decoder/blob/main/ipfs_car_decoder/decoder.py#L163). It's doing a test on the node type and at the moment it seems that it can only do a bytes export on UnixFS files. Weirdly enough, in the unit tests i've added, i call stream_bytes on the CID of a UnixFS directory with a single file in it and it works (not sure yet why it does, and my test should use a file's CID, sorry if the docs are misleading).

Could you try calling *stream_bytes()* on the CID of a file located in one of the directories ?

Does calling *export_to_directory()* work ?

Tried to export it to a CAR but it's taking a while !

**Comment by pinnaculum** [comment]
Ok, the export just finished. So indeed, by passing the CID of the *1700842786271269.parquet* file, which has the CID *bafybeibzgqwfr63bhtdfvx4atsrmge7g7zvtdmqss6d5zwzel3ujbfe76q*, the bytes export is working, here's the script i use:

```python
from pathlib import Path
from aioipfs import AsyncIPFS
from aioipfs import util
from asyncio import run

# Root CID
cid = 'bafybeiajgoqpcayvds6lgvit5r5blitjdgjrrkedmiyckblykchkzlfwc4'

# CID of the .parquet file
file_cid = 'bafybeibzgqwfr63bhtdfvx4atsrmge7g7zvtdmqss6d5zwzel3ujbfe76q'


async def process_car_file():
    client = AsyncIPFS()
    car_path = Path(f'{cid}.car')

    try:
        await client.dag.export(
            cid, output_path=car_path
        )

        data = await util.car_bytes(
            util.car_open(car_path),
            file_cid
        )
        assert data

        await client.close()
    except Exception as e:
        print(f"Error occurred: {e}")

run(process_car_file())
```

I'll update the docs to explain that the CID passed to *stream_bytes()* must be the CID of a UnixFS file.

**Comment by pinnaculum** [comment]
> @pinnaculum ahh, got it. That makes sense. Appreciate the quick response and also the demo code. Thanks for the help!

Thank you for raising this issue. The support for CAR is really recent, don't hesitate to share ideas on how to improve it, APIs that could be added, etc ... By the way, due to a typing hints issue with one of py-ipfs-car-decoder's dependencies (the *bases* package), you need at least python 3.10 to use the CAR decoder package.

**Comment by dtbuchholz** [comment]
Forsure, I'll keep you posted if I have any ideas / features. And got it, fwiw, I was using 3.10.10 so no issues on that aspect!
